### ISSUE TITLE
To review (as of last day at CEPR)

### ISSUE THREAD

**Issue by youngsaver** [youngsaver/predicting_dropouts#1]
The full draft of the code is complete (including write-up). I haven’t combed through for grammar yet: was going to wait until you’ve taken a look to make sure I’m on the right track.  There were several points I wanted to clarify, fix, and/or get advice about:

1. I included the logistic regression to inform my decisions on the missing data. However, I was hoping you could take a look over it to make sure the logic is reasonable.
2. I provided a mock data description in the guide, but I'm not sure it's accurate. For example, any variable including `_11` I assumed to mean their value in 11th grade. I'm not sure about that. We still also need to create a document in the `man` folder for to describe this data.
3. I transformed several predictors to make them more normal, and I stated that normalizing predictors can help with prediction power in the model. However, I have read mixed statements on that point for the Lasso. Is it true that transforming the predictors may help prediction power for the Lasso?
4. The cross-validation I coded manually takes a long time to run (after putting in polynomial features and indicators for missing data). I tried to make it more efficient, but it's still very slow on my machine. Is there a way to make it more efficient while retaining in demonstrability? 
5. Do you have a good image to describe overfitting in a simple regression (like the one at the top of this article: https://medium.com/greyatom/what-is-underfitting-and-overfitting-in-machine-learning-and-how-to-deal-with-it-6803a989c76). I discuss an image in the write-up to demonstrate overfitting. Instead of making one from scratch, I was hoping you'd happen to have one we could use :).

**Comment by jknowles** [comment]
1. The logistic section as a number of specific points I think we should explain with a bit more depth. I will file that under a separate issue / PR some suggested changes as well. 

2. We can update the mock guide using the data codebook I sent you. 

3. Transformation makes computation smoother, but does not really improve accuracy of the model for lasso or regularized regression models generally. But it is a good idea because it greatly speeds up computation and makes other algorithms perform better. Will add text to reflect this. 

4. The only way to speed up CV is to decrease the amount of time in each loop, or run each loop on a separate processing core. We can add some parallel computing code to speed things up, the code will remain expressive, but there will be a bit of additional package overhead to connect up to parallel processing. I will add this. 

5. Slacked you an image I think might work, but needs some explanation in the text. It's not the best, so if you think it's not better just let me know and we'll see if we can come up with anything else!

**Comment by youngsaver** [comment]
All these fixes have been made.
